# Generated by Django 3.2.7 on 2021-12-26 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=150, unique=True, verbose_name='Номер телефона')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='TradingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_points', to='store.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата посещения')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Широта')),
                ('logitude', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Долгота')),
                ('trading_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='store.tradingpoint', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Посещения',
                'verbose_name_plural': 'Посещении',
            },
        ),
    ]
