# Generated by Django 3.2.7 on 2021-12-26 12:53

from django.db import migrations
import store.managers


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', store.managers.EmployeeManager()),
            ],
        ),
    ]
